wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.1
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1731345766.0
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 53
      - 55
      - 77
      3:
      - 23
      - 37
      4: 3.12.1
      5: 0.16.6
      8:
      - 3
      - 5
      13: windows-amd64
AL4GE:
  desc: null
  value: false
budget_per_iter:
  desc: null
  value: 8
classifier:
  desc: null
  value: LogisticRegression
coef:
  desc: null
  value:
  - true
  - true
  - false
  - false
dataset:
  desc: null
  value: lab_dataset_2000.pkl
gnn_epochs:
  desc: null
  value: 5
gnn_hidden:
  desc: null
  value: 32
iterations:
  desc: null
  value: 100
n_clusters:
  desc: null
  value: 2
quantile:
  desc: null
  value: 0.1
sim_metric:
  desc: null
  value: cosine
uncertainty_measures:
  desc: null
  value:
  - entropy_e
  - density_kmean
  - pagerank
  - area_variance
use_gnn:
  desc: null
  value: true
wandb:
  desc: null
  value: 1
